#! /usr/bin/env python3
from parserecipe import parserecipe
import pyjade, pyjade.ext.jinja
import jinja2
from os import path
import sys

with open(path.join(path.dirname(path.realpath(__file__)), 'recipe.jade')) as f:
	JADE_TEMPLATE=f.read()
template = jinja2.Template(
	pyjade.utils.process(JADE_TEMPLATE, compiler=pyjade.ext.jinja.Compiler)
)
template.environment.globals[pyjade.ext.jinja.ATTRS_FUNC] = pyjade.ext.jinja.attrs
template.environment.globals[pyjade.ext.jinja.ITER_FUNC] = pyjade.ext.jinja.iteration

if len(sys.argv) == 2:
	f = open(sys.argv[1], 'r')
elif len(sys.argv) == 1:
	f = sys.stdin
else:
	print('Usage: '+sys.argv[0]+' [file]')
	sys.exit(1)

print(template.render(recipe=parserecipe(f)))
