#! /usr/bin/env python3
from parserecipe import parserecipe
import pyjade, pyjade.ext.jinja
import jinja2
from os import path
import sys

with open(path.join(path.dirname(path.realpath(__file__)), 'recipe.jade')) as f:
	JADE_TEMPLATE=f.read()
template = jinja2.Template(
	pyjade.utils.process(JADE_TEMPLATE, compiler=pyjade.ext.jinja.Compiler)
)
template.environment.globals[pyjade.ext.jinja.ATTRS_FUNC] = pyjade.ext.jinja.attrs
template.environment.globals[pyjade.ext.jinja.ITER_FUNC] = pyjade.ext.jinja.iteration
print(template.render(recipe=parserecipe(open(sys.argv[1], 'r'))))
